// Code generated by protoc-gen-go-mrpc. DO NOT EDIT.

package first

import (
	//std
	"context"

	//third
	"github.com/chenjie199234/Corelib/rpc/mrpc"
	"google.golang.org/protobuf/proto"

	//project
	"protoc-gen-go-mrpc/second"
)

type MrpcTestService struct {
	Hello func(context.Context, HelloReq) (HelloResp, *mrpc.MsgErr)
	Kiss  func(context.Context, second.KissReq) (second.KissResp, *mrpc.MsgErr)
	Bye   func(context.Context, second.ByeReq) (second.ByeResp, *mrpc.MsgErr)
}

var PathMrpcTestHello = "/Test/Hello"
var PathMrpcTestKiss = "/Test/Kiss"
var PathMrpcTestBye = "/Test/Bye"

func RegisterMrpcTestService(engine *mrpc.Server, instance *MrpcTestService) {
	//Hello
	if instance.Hello == nil {
	} else {
	}
	//Kiss
	if instance.Kiss == nil {
	} else {
	}
	//Bye
	if instance.Bye == nil {
	} else {
	}
}
