//protoc -I ../../../pbex -I . --go-crpc_out=paths=source_relative:. *.proto
edition = "2024";
package test;
option go_package="github.com/chenjie199234/Corelib/web/protoc-gen-go-crpc/test;test";
import option "pbex.proto";
service Test {
	rpc Call(Callreq)returns(Callresp){
		option (pbex.method)="crpc";
	}
	rpc ClientStream(stream ClientStreamreq)returns(ClientStreamresp){
		option (pbex.method)="crpc";
	}
	rpc ServerStream(ServerStreamreq)returns(stream ServerStreamresp){
		option (pbex.method)="crpc";
	}
	rpc AllStream(stream AllStreamreq)returns(stream AllStreamresp){
		option (pbex.method)="crpc";
	}
}
message Callreq{
	uint64 u64=1[(pbex.uint_gt)=10];
}
message Callresp{
	bool status=1;
}
message ClientStreamreq{
	uint64 u64=1[(pbex.uint_gt)=10];
}
message ClientStreamresp{
	bool status=1;
}
message ServerStreamreq{
	uint64 u64=1[(pbex.uint_gt)=10];
}
message ServerStreamresp{
	bool status=1;
}
message AllStreamreq{
	uint64 u64=1[(pbex.uint_gt)=10];
}
message AllStreamresp{
	bool status=1;
}
