// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.21.0-devel
// 	protoc        v3.11.4
// source: msg.proto

package stream

import (
	proto "github.com/golang/protobuf/proto"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// This is a compile-time assertion that a sufficiently up-to-date version
// of the legacy proto package is being used.
const _ = proto.ProtoPackageIsVersion4

type TotalMsgType int32

const (
	TotalMsgType_HEART  TotalMsgType = 0
	TotalMsgType_VERIFY TotalMsgType = 1
	TotalMsgType_USER   TotalMsgType = 2
)

// Enum value maps for TotalMsgType.
var (
	TotalMsgType_name = map[int32]string{
		0: "HEART",
		1: "VERIFY",
		2: "USER",
	}
	TotalMsgType_value = map[string]int32{
		"HEART":  0,
		"VERIFY": 1,
		"USER":   2,
	}
)

func (x TotalMsgType) Enum() *TotalMsgType {
	p := new(TotalMsgType)
	*p = x
	return p
}

func (x TotalMsgType) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (TotalMsgType) Descriptor() protoreflect.EnumDescriptor {
	return file_msg_proto_enumTypes[0].Descriptor()
}

func (TotalMsgType) Type() protoreflect.EnumType {
	return &file_msg_proto_enumTypes[0]
}

func (x TotalMsgType) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use TotalMsgType.Descriptor instead.
func (TotalMsgType) EnumDescriptor() ([]byte, []int) {
	return file_msg_proto_rawDescGZIP(), []int{0}
}

type TotalMsg struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Totaltype TotalMsgType `protobuf:"varint,1,opt,name=totaltype,proto3,enum=stream.TotalMsgType" json:"totaltype,omitempty"`
	Sender    string       `protobuf:"bytes,2,opt,name=sender,proto3" json:"sender,omitempty"`
	Starttime int64        `protobuf:"varint,3,opt,name=starttime,proto3" json:"starttime,omitempty"`
	// Types that are assignable to Msg:
	//	*TotalMsg_Heart
	//	*TotalMsg_Verify
	//	*TotalMsg_User
	Msg isTotalMsg_Msg `protobuf_oneof:"msg"`
}

func (x *TotalMsg) Reset() {
	*x = TotalMsg{}
	if protoimpl.UnsafeEnabled {
		mi := &file_msg_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *TotalMsg) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TotalMsg) ProtoMessage() {}

func (x *TotalMsg) ProtoReflect() protoreflect.Message {
	mi := &file_msg_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TotalMsg.ProtoReflect.Descriptor instead.
func (*TotalMsg) Descriptor() ([]byte, []int) {
	return file_msg_proto_rawDescGZIP(), []int{0}
}

func (x *TotalMsg) GetTotaltype() TotalMsgType {
	if x != nil {
		return x.Totaltype
	}
	return TotalMsgType_HEART
}

func (x *TotalMsg) GetSender() string {
	if x != nil {
		return x.Sender
	}
	return ""
}

func (x *TotalMsg) GetStarttime() int64 {
	if x != nil {
		return x.Starttime
	}
	return 0
}

func (m *TotalMsg) GetMsg() isTotalMsg_Msg {
	if m != nil {
		return m.Msg
	}
	return nil
}

func (x *TotalMsg) GetHeart() *HeartMsg {
	if x, ok := x.GetMsg().(*TotalMsg_Heart); ok {
		return x.Heart
	}
	return nil
}

func (x *TotalMsg) GetVerify() *VerifyMsg {
	if x, ok := x.GetMsg().(*TotalMsg_Verify); ok {
		return x.Verify
	}
	return nil
}

func (x *TotalMsg) GetUser() *UserMsg {
	if x, ok := x.GetMsg().(*TotalMsg_User); ok {
		return x.User
	}
	return nil
}

type isTotalMsg_Msg interface {
	isTotalMsg_Msg()
}

type TotalMsg_Heart struct {
	Heart *HeartMsg `protobuf:"bytes,4,opt,name=heart,proto3,oneof"`
}

type TotalMsg_Verify struct {
	Verify *VerifyMsg `protobuf:"bytes,5,opt,name=verify,proto3,oneof"`
}

type TotalMsg_User struct {
	User *UserMsg `protobuf:"bytes,6,opt,name=user,proto3,oneof"`
}

func (*TotalMsg_Heart) isTotalMsg_Msg() {}

func (*TotalMsg_Verify) isTotalMsg_Msg() {}

func (*TotalMsg_User) isTotalMsg_Msg() {}

type HeartMsg struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Timestamp int64 `protobuf:"varint,1,opt,name=timestamp,proto3" json:"timestamp,omitempty"`
}

func (x *HeartMsg) Reset() {
	*x = HeartMsg{}
	if protoimpl.UnsafeEnabled {
		mi := &file_msg_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *HeartMsg) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*HeartMsg) ProtoMessage() {}

func (x *HeartMsg) ProtoReflect() protoreflect.Message {
	mi := &file_msg_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use HeartMsg.ProtoReflect.Descriptor instead.
func (*HeartMsg) Descriptor() ([]byte, []int) {
	return file_msg_proto_rawDescGZIP(), []int{1}
}

func (x *HeartMsg) GetTimestamp() int64 {
	if x != nil {
		return x.Timestamp
	}
	return 0
}

type VerifyMsg struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Verifydata []byte `protobuf:"bytes,1,opt,name=verifydata,proto3" json:"verifydata,omitempty"`
}

func (x *VerifyMsg) Reset() {
	*x = VerifyMsg{}
	if protoimpl.UnsafeEnabled {
		mi := &file_msg_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *VerifyMsg) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*VerifyMsg) ProtoMessage() {}

func (x *VerifyMsg) ProtoReflect() protoreflect.Message {
	mi := &file_msg_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use VerifyMsg.ProtoReflect.Descriptor instead.
func (*VerifyMsg) Descriptor() ([]byte, []int) {
	return file_msg_proto_rawDescGZIP(), []int{2}
}

func (x *VerifyMsg) GetVerifydata() []byte {
	if x != nil {
		return x.Verifydata
	}
	return nil
}

type UserMsg struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Userdata []byte `protobuf:"bytes,1,opt,name=userdata,proto3" json:"userdata,omitempty"`
}

func (x *UserMsg) Reset() {
	*x = UserMsg{}
	if protoimpl.UnsafeEnabled {
		mi := &file_msg_proto_msgTypes[3]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *UserMsg) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UserMsg) ProtoMessage() {}

func (x *UserMsg) ProtoReflect() protoreflect.Message {
	mi := &file_msg_proto_msgTypes[3]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UserMsg.ProtoReflect.Descriptor instead.
func (*UserMsg) Descriptor() ([]byte, []int) {
	return file_msg_proto_rawDescGZIP(), []int{3}
}

func (x *UserMsg) GetUserdata() []byte {
	if x != nil {
		return x.Userdata
	}
	return nil
}

var File_msg_proto protoreflect.FileDescriptor

var file_msg_proto_rawDesc = []byte{
	0x0a, 0x09, 0x6d, 0x73, 0x67, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x06, 0x73, 0x74, 0x72,
	0x65, 0x61, 0x6d, 0x22, 0xf9, 0x01, 0x0a, 0x08, 0x54, 0x6f, 0x74, 0x61, 0x6c, 0x4d, 0x73, 0x67,
	0x12, 0x32, 0x0a, 0x09, 0x74, 0x6f, 0x74, 0x61, 0x6c, 0x74, 0x79, 0x70, 0x65, 0x18, 0x01, 0x20,
	0x01, 0x28, 0x0e, 0x32, 0x14, 0x2e, 0x73, 0x74, 0x72, 0x65, 0x61, 0x6d, 0x2e, 0x54, 0x6f, 0x74,
	0x61, 0x6c, 0x4d, 0x73, 0x67, 0x54, 0x79, 0x70, 0x65, 0x52, 0x09, 0x74, 0x6f, 0x74, 0x61, 0x6c,
	0x74, 0x79, 0x70, 0x65, 0x12, 0x16, 0x0a, 0x06, 0x73, 0x65, 0x6e, 0x64, 0x65, 0x72, 0x18, 0x02,
	0x20, 0x01, 0x28, 0x09, 0x52, 0x06, 0x73, 0x65, 0x6e, 0x64, 0x65, 0x72, 0x12, 0x1c, 0x0a, 0x09,
	0x73, 0x74, 0x61, 0x72, 0x74, 0x74, 0x69, 0x6d, 0x65, 0x18, 0x03, 0x20, 0x01, 0x28, 0x03, 0x52,
	0x09, 0x73, 0x74, 0x61, 0x72, 0x74, 0x74, 0x69, 0x6d, 0x65, 0x12, 0x28, 0x0a, 0x05, 0x68, 0x65,
	0x61, 0x72, 0x74, 0x18, 0x04, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x10, 0x2e, 0x73, 0x74, 0x72, 0x65,
	0x61, 0x6d, 0x2e, 0x48, 0x65, 0x61, 0x72, 0x74, 0x4d, 0x73, 0x67, 0x48, 0x00, 0x52, 0x05, 0x68,
	0x65, 0x61, 0x72, 0x74, 0x12, 0x2b, 0x0a, 0x06, 0x76, 0x65, 0x72, 0x69, 0x66, 0x79, 0x18, 0x05,
	0x20, 0x01, 0x28, 0x0b, 0x32, 0x11, 0x2e, 0x73, 0x74, 0x72, 0x65, 0x61, 0x6d, 0x2e, 0x56, 0x65,
	0x72, 0x69, 0x66, 0x79, 0x4d, 0x73, 0x67, 0x48, 0x00, 0x52, 0x06, 0x76, 0x65, 0x72, 0x69, 0x66,
	0x79, 0x12, 0x25, 0x0a, 0x04, 0x75, 0x73, 0x65, 0x72, 0x18, 0x06, 0x20, 0x01, 0x28, 0x0b, 0x32,
	0x0f, 0x2e, 0x73, 0x74, 0x72, 0x65, 0x61, 0x6d, 0x2e, 0x55, 0x73, 0x65, 0x72, 0x4d, 0x73, 0x67,
	0x48, 0x00, 0x52, 0x04, 0x75, 0x73, 0x65, 0x72, 0x42, 0x05, 0x0a, 0x03, 0x6d, 0x73, 0x67, 0x22,
	0x28, 0x0a, 0x08, 0x48, 0x65, 0x61, 0x72, 0x74, 0x4d, 0x73, 0x67, 0x12, 0x1c, 0x0a, 0x09, 0x74,
	0x69, 0x6d, 0x65, 0x73, 0x74, 0x61, 0x6d, 0x70, 0x18, 0x01, 0x20, 0x01, 0x28, 0x03, 0x52, 0x09,
	0x74, 0x69, 0x6d, 0x65, 0x73, 0x74, 0x61, 0x6d, 0x70, 0x22, 0x2b, 0x0a, 0x09, 0x56, 0x65, 0x72,
	0x69, 0x66, 0x79, 0x4d, 0x73, 0x67, 0x12, 0x1e, 0x0a, 0x0a, 0x76, 0x65, 0x72, 0x69, 0x66, 0x79,
	0x64, 0x61, 0x74, 0x61, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0c, 0x52, 0x0a, 0x76, 0x65, 0x72, 0x69,
	0x66, 0x79, 0x64, 0x61, 0x74, 0x61, 0x22, 0x25, 0x0a, 0x07, 0x55, 0x73, 0x65, 0x72, 0x4d, 0x73,
	0x67, 0x12, 0x1a, 0x0a, 0x08, 0x75, 0x73, 0x65, 0x72, 0x64, 0x61, 0x74, 0x61, 0x18, 0x01, 0x20,
	0x01, 0x28, 0x0c, 0x52, 0x08, 0x75, 0x73, 0x65, 0x72, 0x64, 0x61, 0x74, 0x61, 0x2a, 0x2f, 0x0a,
	0x0c, 0x54, 0x6f, 0x74, 0x61, 0x6c, 0x4d, 0x73, 0x67, 0x54, 0x79, 0x70, 0x65, 0x12, 0x09, 0x0a,
	0x05, 0x48, 0x45, 0x41, 0x52, 0x54, 0x10, 0x00, 0x12, 0x0a, 0x0a, 0x06, 0x56, 0x45, 0x52, 0x49,
	0x46, 0x59, 0x10, 0x01, 0x12, 0x08, 0x0a, 0x04, 0x55, 0x53, 0x45, 0x52, 0x10, 0x02, 0x42, 0x0a,
	0x5a, 0x08, 0x2e, 0x3b, 0x73, 0x74, 0x72, 0x65, 0x61, 0x6d, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74,
	0x6f, 0x33,
}

var (
	file_msg_proto_rawDescOnce sync.Once
	file_msg_proto_rawDescData = file_msg_proto_rawDesc
)

func file_msg_proto_rawDescGZIP() []byte {
	file_msg_proto_rawDescOnce.Do(func() {
		file_msg_proto_rawDescData = protoimpl.X.CompressGZIP(file_msg_proto_rawDescData)
	})
	return file_msg_proto_rawDescData
}

var file_msg_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_msg_proto_msgTypes = make([]protoimpl.MessageInfo, 4)
var file_msg_proto_goTypes = []interface{}{
	(TotalMsgType)(0), // 0: stream.TotalMsgType
	(*TotalMsg)(nil),  // 1: stream.TotalMsg
	(*HeartMsg)(nil),  // 2: stream.HeartMsg
	(*VerifyMsg)(nil), // 3: stream.VerifyMsg
	(*UserMsg)(nil),   // 4: stream.UserMsg
}
var file_msg_proto_depIdxs = []int32{
	0, // 0: stream.TotalMsg.totaltype:type_name -> stream.TotalMsgType
	2, // 1: stream.TotalMsg.heart:type_name -> stream.HeartMsg
	3, // 2: stream.TotalMsg.verify:type_name -> stream.VerifyMsg
	4, // 3: stream.TotalMsg.user:type_name -> stream.UserMsg
	4, // [4:4] is the sub-list for method output_type
	4, // [4:4] is the sub-list for method input_type
	4, // [4:4] is the sub-list for extension type_name
	4, // [4:4] is the sub-list for extension extendee
	0, // [0:4] is the sub-list for field type_name
}

func init() { file_msg_proto_init() }
func file_msg_proto_init() {
	if File_msg_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_msg_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*TotalMsg); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_msg_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*HeartMsg); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_msg_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*VerifyMsg); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_msg_proto_msgTypes[3].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*UserMsg); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	file_msg_proto_msgTypes[0].OneofWrappers = []interface{}{
		(*TotalMsg_Heart)(nil),
		(*TotalMsg_Verify)(nil),
		(*TotalMsg_User)(nil),
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_msg_proto_rawDesc,
			NumEnums:      1,
			NumMessages:   4,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_msg_proto_goTypes,
		DependencyIndexes: file_msg_proto_depIdxs,
		EnumInfos:         file_msg_proto_enumTypes,
		MessageInfos:      file_msg_proto_msgTypes,
	}.Build()
	File_msg_proto = out.File
	file_msg_proto_rawDesc = nil
	file_msg_proto_goTypes = nil
	file_msg_proto_depIdxs = nil
}
