edition = "2024";
package crpc;
option go_package="github.com/chenjie199234/Corelib/crpc;crpc";
import "cerror/cerror.proto";

enum MsgType{
	INIT=0;//only from client to server
	INIT_SUCCESS=1;//only from server to client
	SEND=2;
	CLOSE_SEND=3;
	CLOSE_RECV=4;
	CLOSE_RECV_SEND=5;
}
enum Encoder{
	UNKNOWN=0;
	PROTOBUF=1;
	JSON=2;
}
message Msg {
	message Header {
		uint64 callid=1;
		string path=2;
		MsgType type=3;
		int64 deadline=4;
		map<string,string> metadata=5;
		map<string,string> tracedata=6;
	}
	message Body {
		bytes body=1;
		Encoder body_encoder=2;
		cerror.Error error=3;//only from server to client
	}
	Header h=1;
	Body b=2;
}
