// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        v6.30.2
// source: crpc/msg.proto

package crpc

import (
	cerror "github.com/chenjie199234/Corelib/cerror"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type MsgType int32

const (
	MsgType_Init          MsgType = 0
	MsgType_Send          MsgType = 1
	MsgType_CloseSend     MsgType = 2
	MsgType_CloseRecv     MsgType = 3
	MsgType_CloseRecvSend MsgType = 4
)

// Enum value maps for MsgType.
var (
	MsgType_name = map[int32]string{
		0: "Init",
		1: "Send",
		2: "CloseSend",
		3: "CloseRecv",
		4: "CloseRecvSend",
	}
	MsgType_value = map[string]int32{
		"Init":          0,
		"Send":          1,
		"CloseSend":     2,
		"CloseRecv":     3,
		"CloseRecvSend": 4,
	}
)

func (x MsgType) Enum() *MsgType {
	p := new(MsgType)
	*p = x
	return p
}

func (x MsgType) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (MsgType) Descriptor() protoreflect.EnumDescriptor {
	return file_crpc_msg_proto_enumTypes[0].Descriptor()
}

func (MsgType) Type() protoreflect.EnumType {
	return &file_crpc_msg_proto_enumTypes[0]
}

func (x MsgType) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use MsgType.Descriptor instead.
func (MsgType) EnumDescriptor() ([]byte, []int) {
	return file_crpc_msg_proto_rawDescGZIP(), []int{0}
}

type Encoder int32

const (
	Encoder_Unknown  Encoder = 0
	Encoder_Protobuf Encoder = 1
	Encoder_Json     Encoder = 2
)

// Enum value maps for Encoder.
var (
	Encoder_name = map[int32]string{
		0: "Unknown",
		1: "Protobuf",
		2: "Json",
	}
	Encoder_value = map[string]int32{
		"Unknown":  0,
		"Protobuf": 1,
		"Json":     2,
	}
)

func (x Encoder) Enum() *Encoder {
	p := new(Encoder)
	*p = x
	return p
}

func (x Encoder) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (Encoder) Descriptor() protoreflect.EnumDescriptor {
	return file_crpc_msg_proto_enumTypes[1].Descriptor()
}

func (Encoder) Type() protoreflect.EnumType {
	return &file_crpc_msg_proto_enumTypes[1]
}

func (x Encoder) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use Encoder.Descriptor instead.
func (Encoder) EnumDescriptor() ([]byte, []int) {
	return file_crpc_msg_proto_rawDescGZIP(), []int{1}
}

type Msg struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	H             *MsgHeader             `protobuf:"bytes,1,opt,name=h,proto3" json:"h,omitempty"`
	B             *MsgBody               `protobuf:"bytes,2,opt,name=b,proto3" json:"b,omitempty"`
	WithB         bool                   `protobuf:"varint,3,opt,name=with_b,json=withB,proto3" json:"with_b,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Msg) Reset() {
	*x = Msg{}
	mi := &file_crpc_msg_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Msg) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Msg) ProtoMessage() {}

func (x *Msg) ProtoReflect() protoreflect.Message {
	mi := &file_crpc_msg_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Msg.ProtoReflect.Descriptor instead.
func (*Msg) Descriptor() ([]byte, []int) {
	return file_crpc_msg_proto_rawDescGZIP(), []int{0}
}

func (x *Msg) GetH() *MsgHeader {
	if x != nil {
		return x.H
	}
	return nil
}

func (x *Msg) GetB() *MsgBody {
	if x != nil {
		return x.B
	}
	return nil
}

func (x *Msg) GetWithB() bool {
	if x != nil {
		return x.WithB
	}
	return false
}

type MsgHeader struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Callid        uint64                 `protobuf:"varint,1,opt,name=callid,proto3" json:"callid,omitempty"`
	Path          string                 `protobuf:"bytes,2,opt,name=path,proto3" json:"path,omitempty"`
	Type          MsgType                `protobuf:"varint,3,opt,name=type,proto3,enum=crpc.MsgType" json:"type,omitempty"`
	Deadline      int64                  `protobuf:"varint,4,opt,name=deadline,proto3" json:"deadline,omitempty"`
	Metadata      map[string]string      `protobuf:"bytes,5,rep,name=metadata,proto3" json:"metadata,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	Tracedata     map[string]string      `protobuf:"bytes,6,rep,name=tracedata,proto3" json:"tracedata,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	Traildata     map[string]string      `protobuf:"bytes,7,rep,name=traildata,proto3" json:"traildata,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"` //only from server to client
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *MsgHeader) Reset() {
	*x = MsgHeader{}
	mi := &file_crpc_msg_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *MsgHeader) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MsgHeader) ProtoMessage() {}

func (x *MsgHeader) ProtoReflect() protoreflect.Message {
	mi := &file_crpc_msg_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MsgHeader.ProtoReflect.Descriptor instead.
func (*MsgHeader) Descriptor() ([]byte, []int) {
	return file_crpc_msg_proto_rawDescGZIP(), []int{0, 0}
}

func (x *MsgHeader) GetCallid() uint64 {
	if x != nil {
		return x.Callid
	}
	return 0
}

func (x *MsgHeader) GetPath() string {
	if x != nil {
		return x.Path
	}
	return ""
}

func (x *MsgHeader) GetType() MsgType {
	if x != nil {
		return x.Type
	}
	return MsgType_Init
}

func (x *MsgHeader) GetDeadline() int64 {
	if x != nil {
		return x.Deadline
	}
	return 0
}

func (x *MsgHeader) GetMetadata() map[string]string {
	if x != nil {
		return x.Metadata
	}
	return nil
}

func (x *MsgHeader) GetTracedata() map[string]string {
	if x != nil {
		return x.Tracedata
	}
	return nil
}

func (x *MsgHeader) GetTraildata() map[string]string {
	if x != nil {
		return x.Traildata
	}
	return nil
}

type MsgBody struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Body          []byte                 `protobuf:"bytes,1,opt,name=body,proto3" json:"body,omitempty"`
	BodyEncoder   Encoder                `protobuf:"varint,2,opt,name=body_encoder,json=bodyEncoder,proto3,enum=crpc.Encoder" json:"body_encoder,omitempty"`
	Error         *cerror.Error          `protobuf:"bytes,3,opt,name=error,proto3" json:"error,omitempty"` //only from server to client
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *MsgBody) Reset() {
	*x = MsgBody{}
	mi := &file_crpc_msg_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *MsgBody) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MsgBody) ProtoMessage() {}

func (x *MsgBody) ProtoReflect() protoreflect.Message {
	mi := &file_crpc_msg_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MsgBody.ProtoReflect.Descriptor instead.
func (*MsgBody) Descriptor() ([]byte, []int) {
	return file_crpc_msg_proto_rawDescGZIP(), []int{0, 1}
}

func (x *MsgBody) GetBody() []byte {
	if x != nil {
		return x.Body
	}
	return nil
}

func (x *MsgBody) GetBodyEncoder() Encoder {
	if x != nil {
		return x.BodyEncoder
	}
	return Encoder_Unknown
}

func (x *MsgBody) GetError() *cerror.Error {
	if x != nil {
		return x.Error
	}
	return nil
}

var File_crpc_msg_proto protoreflect.FileDescriptor

const file_crpc_msg_proto_rawDesc = "" +
	"\n" +
	"\x0ecrpc/msg.proto\x12\x04crpc\x1a\x13cerror/cerror.proto\"\xb6\x05\n" +
	"\x03msg\x12\x1e\n" +
	"\x01h\x18\x01 \x01(\v2\x10.crpc.msg.headerR\x01h\x12\x1c\n" +
	"\x01b\x18\x02 \x01(\v2\x0e.crpc.msg.bodyR\x01b\x12\x15\n" +
	"\x06with_b\x18\x03 \x01(\bR\x05withB\x1a\xe6\x03\n" +
	"\x06header\x12\x16\n" +
	"\x06callid\x18\x01 \x01(\x04R\x06callid\x12\x12\n" +
	"\x04path\x18\x02 \x01(\tR\x04path\x12!\n" +
	"\x04type\x18\x03 \x01(\x0e2\r.crpc.MsgTypeR\x04type\x12\x1a\n" +
	"\bdeadline\x18\x04 \x01(\x03R\bdeadline\x12:\n" +
	"\bmetadata\x18\x05 \x03(\v2\x1e.crpc.msg.header.MetadataEntryR\bmetadata\x12=\n" +
	"\ttracedata\x18\x06 \x03(\v2\x1f.crpc.msg.header.TracedataEntryR\ttracedata\x12=\n" +
	"\ttraildata\x18\a \x03(\v2\x1f.crpc.msg.header.TraildataEntryR\ttraildata\x1a;\n" +
	"\rMetadataEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01\x1a<\n" +
	"\x0eTracedataEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01\x1a<\n" +
	"\x0eTraildataEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01\x1aq\n" +
	"\x04body\x12\x12\n" +
	"\x04body\x18\x01 \x01(\fR\x04body\x120\n" +
	"\fbody_encoder\x18\x02 \x01(\x0e2\r.crpc.EncoderR\vbodyEncoder\x12#\n" +
	"\x05error\x18\x03 \x01(\v2\r.cerror.ErrorR\x05error*N\n" +
	"\aMsgType\x12\b\n" +
	"\x04Init\x10\x00\x12\b\n" +
	"\x04Send\x10\x01\x12\r\n" +
	"\tCloseSend\x10\x02\x12\r\n" +
	"\tCloseRecv\x10\x03\x12\x11\n" +
	"\rCloseRecvSend\x10\x04*.\n" +
	"\aEncoder\x12\v\n" +
	"\aUnknown\x10\x00\x12\f\n" +
	"\bProtobuf\x10\x01\x12\b\n" +
	"\x04Json\x10\x02B,Z*github.com/chenjie199234/Corelib/crpc;crpcb\x06proto3"

var (
	file_crpc_msg_proto_rawDescOnce sync.Once
	file_crpc_msg_proto_rawDescData []byte
)

func file_crpc_msg_proto_rawDescGZIP() []byte {
	file_crpc_msg_proto_rawDescOnce.Do(func() {
		file_crpc_msg_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_crpc_msg_proto_rawDesc), len(file_crpc_msg_proto_rawDesc)))
	})
	return file_crpc_msg_proto_rawDescData
}

var file_crpc_msg_proto_enumTypes = make([]protoimpl.EnumInfo, 2)
var file_crpc_msg_proto_msgTypes = make([]protoimpl.MessageInfo, 6)
var file_crpc_msg_proto_goTypes = []any{
	(MsgType)(0),         // 0: crpc.MsgType
	(Encoder)(0),         // 1: crpc.Encoder
	(*Msg)(nil),          // 2: crpc.msg
	(*MsgHeader)(nil),    // 3: crpc.msg.header
	(*MsgBody)(nil),      // 4: crpc.msg.body
	nil,                  // 5: crpc.msg.header.MetadataEntry
	nil,                  // 6: crpc.msg.header.TracedataEntry
	nil,                  // 7: crpc.msg.header.TraildataEntry
	(*cerror.Error)(nil), // 8: cerror.Error
}
var file_crpc_msg_proto_depIdxs = []int32{
	3, // 0: crpc.msg.h:type_name -> crpc.msg.header
	4, // 1: crpc.msg.b:type_name -> crpc.msg.body
	0, // 2: crpc.msg.header.type:type_name -> crpc.MsgType
	5, // 3: crpc.msg.header.metadata:type_name -> crpc.msg.header.MetadataEntry
	6, // 4: crpc.msg.header.tracedata:type_name -> crpc.msg.header.TracedataEntry
	7, // 5: crpc.msg.header.traildata:type_name -> crpc.msg.header.TraildataEntry
	1, // 6: crpc.msg.body.body_encoder:type_name -> crpc.Encoder
	8, // 7: crpc.msg.body.error:type_name -> cerror.Error
	8, // [8:8] is the sub-list for method output_type
	8, // [8:8] is the sub-list for method input_type
	8, // [8:8] is the sub-list for extension type_name
	8, // [8:8] is the sub-list for extension extendee
	0, // [0:8] is the sub-list for field type_name
}

func init() { file_crpc_msg_proto_init() }
func file_crpc_msg_proto_init() {
	if File_crpc_msg_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_crpc_msg_proto_rawDesc), len(file_crpc_msg_proto_rawDesc)),
			NumEnums:      2,
			NumMessages:   6,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_crpc_msg_proto_goTypes,
		DependencyIndexes: file_crpc_msg_proto_depIdxs,
		EnumInfos:         file_crpc_msg_proto_enumTypes,
		MessageInfos:      file_crpc_msg_proto_msgTypes,
	}.Build()
	File_crpc_msg_proto = out.File
	file_crpc_msg_proto_goTypes = nil
	file_crpc_msg_proto_depIdxs = nil
}
