// Code generated by protoc-gen-gogo. DO NOT EDIT.
// source: message.proto

package logger

import (
	bytes "bytes"
	fmt "fmt"
	proto "github.com/gogo/protobuf/proto"
	io "io"
	math "math"
	math_bits "math/bits"
	reflect "reflect"
	strconv "strconv"
	strings "strings"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.GoGoProtoPackageIsVersion2 // please upgrade the proto package

type MsgType int32

const (
	HEART   MsgType = 0
	VERIFY  MsgType = 1
	LOG     MsgType = 2
	CONFIRM MsgType = 3
	REMOVE  MsgType = 4
)

var MsgType_name = map[int32]string{
	0: "HEART",
	1: "VERIFY",
	2: "LOG",
	3: "CONFIRM",
	4: "REMOVE",
}

var MsgType_value = map[string]int32{
	"HEART":   0,
	"VERIFY":  1,
	"LOG":     2,
	"CONFIRM": 3,
	"REMOVE":  4,
}

func (MsgType) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_33c57e4bae7b9afd, []int{0}
}

type TotalMsg struct {
	Type    MsgType     `protobuf:"varint,1,opt,name=type,proto3,enum=nothing.MsgType" json:"type,omitempty"`
	Verify  *VerifyMsg  `protobuf:"bytes,2,opt,name=verify,proto3" json:"verify,omitempty"`
	Log     *LogMsg     `protobuf:"bytes,3,opt,name=log,proto3" json:"log,omitempty"`
	Confirm *ConfirmMsg `protobuf:"bytes,4,opt,name=confirm,proto3" json:"confirm,omitempty"`
	Remove  *RemoveMsg  `protobuf:"bytes,5,opt,name=remove,proto3" json:"remove,omitempty"`
}

func (m *TotalMsg) Reset()      { *m = TotalMsg{} }
func (*TotalMsg) ProtoMessage() {}
func (*TotalMsg) Descriptor() ([]byte, []int) {
	return fileDescriptor_33c57e4bae7b9afd, []int{0}
}
func (m *TotalMsg) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *TotalMsg) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_TotalMsg.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalTo(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *TotalMsg) XXX_Merge(src proto.Message) {
	xxx_messageInfo_TotalMsg.Merge(m, src)
}
func (m *TotalMsg) XXX_Size() int {
	return m.Size()
}
func (m *TotalMsg) XXX_DiscardUnknown() {
	xxx_messageInfo_TotalMsg.DiscardUnknown(m)
}

var xxx_messageInfo_TotalMsg proto.InternalMessageInfo

func (m *TotalMsg) GetType() MsgType {
	if m != nil {
		return m.Type
	}
	return HEART
}

func (m *TotalMsg) GetVerify() *VerifyMsg {
	if m != nil {
		return m.Verify
	}
	return nil
}

func (m *TotalMsg) GetLog() *LogMsg {
	if m != nil {
		return m.Log
	}
	return nil
}

func (m *TotalMsg) GetConfirm() *ConfirmMsg {
	if m != nil {
		return m.Confirm
	}
	return nil
}

func (m *TotalMsg) GetRemove() *RemoveMsg {
	if m != nil {
		return m.Remove
	}
	return nil
}

type VerifyMsg struct {
}

func (m *VerifyMsg) Reset()      { *m = VerifyMsg{} }
func (*VerifyMsg) ProtoMessage() {}
func (*VerifyMsg) Descriptor() ([]byte, []int) {
	return fileDescriptor_33c57e4bae7b9afd, []int{1}
}
func (m *VerifyMsg) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *VerifyMsg) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_VerifyMsg.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalTo(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *VerifyMsg) XXX_Merge(src proto.Message) {
	xxx_messageInfo_VerifyMsg.Merge(m, src)
}
func (m *VerifyMsg) XXX_Size() int {
	return m.Size()
}
func (m *VerifyMsg) XXX_DiscardUnknown() {
	xxx_messageInfo_VerifyMsg.DiscardUnknown(m)
}

var xxx_messageInfo_VerifyMsg proto.InternalMessageInfo

type LogMsg struct {
	Serverid int64  `protobuf:"varint,1,opt,name=serverid,proto3" json:"serverid,omitempty"`
	Content  []byte `protobuf:"bytes,2,opt,name=content,proto3" json:"content,omitempty"`
	Filename string `protobuf:"bytes,3,opt,name=filename,proto3" json:"filename,omitempty"`
	Line     uint32 `protobuf:"varint,4,opt,name=line,proto3" json:"line,omitempty"`
	Memindex uint32 `protobuf:"varint,5,opt,name=memindex,proto3" json:"memindex,omitempty"`
}

func (m *LogMsg) Reset()      { *m = LogMsg{} }
func (*LogMsg) ProtoMessage() {}
func (*LogMsg) Descriptor() ([]byte, []int) {
	return fileDescriptor_33c57e4bae7b9afd, []int{2}
}
func (m *LogMsg) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *LogMsg) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_LogMsg.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalTo(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *LogMsg) XXX_Merge(src proto.Message) {
	xxx_messageInfo_LogMsg.Merge(m, src)
}
func (m *LogMsg) XXX_Size() int {
	return m.Size()
}
func (m *LogMsg) XXX_DiscardUnknown() {
	xxx_messageInfo_LogMsg.DiscardUnknown(m)
}

var xxx_messageInfo_LogMsg proto.InternalMessageInfo

func (m *LogMsg) GetServerid() int64 {
	if m != nil {
		return m.Serverid
	}
	return 0
}

func (m *LogMsg) GetContent() []byte {
	if m != nil {
		return m.Content
	}
	return nil
}

func (m *LogMsg) GetFilename() string {
	if m != nil {
		return m.Filename
	}
	return ""
}

func (m *LogMsg) GetLine() uint32 {
	if m != nil {
		return m.Line
	}
	return 0
}

func (m *LogMsg) GetMemindex() uint32 {
	if m != nil {
		return m.Memindex
	}
	return 0
}

type ConfirmMsg struct {
	Filename string `protobuf:"bytes,1,opt,name=filename,proto3" json:"filename,omitempty"`
	Line     uint32 `protobuf:"varint,2,opt,name=line,proto3" json:"line,omitempty"`
	Memindex uint32 `protobuf:"varint,3,opt,name=memindex,proto3" json:"memindex,omitempty"`
}

func (m *ConfirmMsg) Reset()      { *m = ConfirmMsg{} }
func (*ConfirmMsg) ProtoMessage() {}
func (*ConfirmMsg) Descriptor() ([]byte, []int) {
	return fileDescriptor_33c57e4bae7b9afd, []int{3}
}
func (m *ConfirmMsg) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *ConfirmMsg) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_ConfirmMsg.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalTo(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *ConfirmMsg) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ConfirmMsg.Merge(m, src)
}
func (m *ConfirmMsg) XXX_Size() int {
	return m.Size()
}
func (m *ConfirmMsg) XXX_DiscardUnknown() {
	xxx_messageInfo_ConfirmMsg.DiscardUnknown(m)
}

var xxx_messageInfo_ConfirmMsg proto.InternalMessageInfo

func (m *ConfirmMsg) GetFilename() string {
	if m != nil {
		return m.Filename
	}
	return ""
}

func (m *ConfirmMsg) GetLine() uint32 {
	if m != nil {
		return m.Line
	}
	return 0
}

func (m *ConfirmMsg) GetMemindex() uint32 {
	if m != nil {
		return m.Memindex
	}
	return 0
}

type RemoveMsg struct {
	Year  int32 `protobuf:"varint,1,opt,name=year,proto3" json:"year,omitempty"`
	Month int32 `protobuf:"varint,2,opt,name=month,proto3" json:"month,omitempty"`
	Day   int32 `protobuf:"varint,3,opt,name=day,proto3" json:"day,omitempty"`
	Hour  int32 `protobuf:"varint,4,opt,name=hour,proto3" json:"hour,omitempty"`
}

func (m *RemoveMsg) Reset()      { *m = RemoveMsg{} }
func (*RemoveMsg) ProtoMessage() {}
func (*RemoveMsg) Descriptor() ([]byte, []int) {
	return fileDescriptor_33c57e4bae7b9afd, []int{4}
}
func (m *RemoveMsg) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *RemoveMsg) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_RemoveMsg.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalTo(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *RemoveMsg) XXX_Merge(src proto.Message) {
	xxx_messageInfo_RemoveMsg.Merge(m, src)
}
func (m *RemoveMsg) XXX_Size() int {
	return m.Size()
}
func (m *RemoveMsg) XXX_DiscardUnknown() {
	xxx_messageInfo_RemoveMsg.DiscardUnknown(m)
}

var xxx_messageInfo_RemoveMsg proto.InternalMessageInfo

func (m *RemoveMsg) GetYear() int32 {
	if m != nil {
		return m.Year
	}
	return 0
}

func (m *RemoveMsg) GetMonth() int32 {
	if m != nil {
		return m.Month
	}
	return 0
}

func (m *RemoveMsg) GetDay() int32 {
	if m != nil {
		return m.Day
	}
	return 0
}

func (m *RemoveMsg) GetHour() int32 {
	if m != nil {
		return m.Hour
	}
	return 0
}

func init() {
	proto.RegisterEnum("nothing.MsgType", MsgType_name, MsgType_value)
	proto.RegisterType((*TotalMsg)(nil), "nothing.TotalMsg")
	proto.RegisterType((*VerifyMsg)(nil), "nothing.VerifyMsg")
	proto.RegisterType((*LogMsg)(nil), "nothing.LogMsg")
	proto.RegisterType((*ConfirmMsg)(nil), "nothing.ConfirmMsg")
	proto.RegisterType((*RemoveMsg)(nil), "nothing.RemoveMsg")
}

func init() { proto.RegisterFile("message.proto", fileDescriptor_33c57e4bae7b9afd) }

var fileDescriptor_33c57e4bae7b9afd = []byte{
	// 448 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x74, 0x92, 0x31, 0x6f, 0xd3, 0x50,
	0x10, 0xc7, 0xfd, 0xe2, 0x38, 0x6e, 0x2e, 0x04, 0xac, 0x83, 0xc1, 0x62, 0x78, 0x2a, 0x11, 0x43,
	0x55, 0x89, 0x0c, 0x85, 0x2f, 0x40, 0xab, 0x14, 0x2a, 0xd5, 0x44, 0x3a, 0x45, 0x11, 0x88, 0xc9,
	0x90, 0x17, 0xc7, 0x52, 0xec, 0x17, 0xd9, 0xa6, 0xc2, 0x1b, 0x33, 0x13, 0x1f, 0x83, 0x8f, 0xc2,
	0x98, 0xb1, 0x62, 0x22, 0xce, 0xc2, 0xd8, 0x8f, 0x80, 0xde, 0x39, 0x35, 0x6a, 0xa5, 0x6c, 0xf7,
	0x3f, 0xff, 0xee, 0x7f, 0xf7, 0xb7, 0x1e, 0xf4, 0x13, 0x95, 0xe7, 0x61, 0xa4, 0x86, 0xab, 0x4c,
	0x17, 0x1a, 0xdd, 0x54, 0x17, 0x8b, 0x38, 0x8d, 0x06, 0xbf, 0x05, 0x1c, 0x4c, 0x74, 0x11, 0x2e,
	0x83, 0x3c, 0xc2, 0xe7, 0xd0, 0x2e, 0xca, 0x95, 0xf2, 0xc5, 0xa1, 0x38, 0x7a, 0x78, 0xe2, 0x0d,
	0x77, 0xd0, 0x30, 0xc8, 0xa3, 0x49, 0xb9, 0x52, 0xc4, 0x5f, 0xf1, 0x18, 0x3a, 0x57, 0x2a, 0x8b,
	0xe7, 0xa5, 0xdf, 0x3a, 0x14, 0x47, 0xbd, 0x13, 0x6c, 0xb8, 0x29, 0xb7, 0x83, 0x3c, 0xa2, 0x1d,
	0x81, 0xcf, 0xc0, 0x5e, 0xea, 0xc8, 0xb7, 0x19, 0x7c, 0xd4, 0x80, 0x97, 0x3a, 0x32, 0x94, 0xf9,
	0x86, 0x2f, 0xc0, 0xfd, 0xac, 0xd3, 0x79, 0x9c, 0x25, 0x7e, 0x9b, 0xb1, 0xc7, 0x0d, 0x76, 0x56,
	0xf7, 0x0d, 0x7a, 0xcb, 0x98, 0xed, 0x99, 0x4a, 0xf4, 0x95, 0xf2, 0x9d, 0x7b, 0xdb, 0x89, 0xdb,
	0xbc, 0xbd, 0x26, 0x06, 0x3d, 0xe8, 0x36, 0x27, 0x0d, 0xbe, 0x0b, 0xe8, 0xd4, 0x7b, 0xf1, 0x29,
	0x1c, 0xe4, 0x2a, 0x33, 0x27, 0xce, 0x38, 0xab, 0x4d, 0x8d, 0x46, 0x9f, 0xcf, 0x29, 0x54, 0x5a,
	0x70, 0xbc, 0x07, 0x74, 0x2b, 0xcd, 0xd4, 0x3c, 0x5e, 0xaa, 0x34, 0x4c, 0x14, 0x07, 0xea, 0x52,
	0xa3, 0x11, 0xa1, 0xbd, 0x8c, 0x53, 0xc5, 0x09, 0xfa, 0xc4, 0xb5, 0xe1, 0x13, 0x95, 0xc4, 0xe9,
	0x4c, 0x7d, 0xe5, 0x5b, 0xfb, 0xd4, 0xe8, 0xc1, 0x7b, 0x80, 0xff, 0xe1, 0xee, 0x38, 0x8b, 0x3d,
	0xce, 0xad, 0x3d, 0xce, 0xf6, 0x3d, 0xe7, 0x8f, 0xd0, 0x6d, 0x7e, 0x84, 0x19, 0x2e, 0x55, 0x98,
	0xb1, 0xa9, 0x43, 0x5c, 0xe3, 0x13, 0x70, 0x12, 0x9d, 0x16, 0x0b, 0x76, 0x74, 0xa8, 0x16, 0xe8,
	0x81, 0x3d, 0x0b, 0x4b, 0x76, 0x73, 0xc8, 0x94, 0x66, 0x76, 0xa1, 0xbf, 0x64, 0x1c, 0xc9, 0x21,
	0xae, 0x8f, 0x4f, 0xc1, 0xdd, 0xbd, 0x05, 0xec, 0x82, 0xf3, 0x76, 0xf4, 0x9a, 0x26, 0x9e, 0x85,
	0x00, 0x9d, 0xe9, 0x88, 0x2e, 0xce, 0x3f, 0x78, 0x02, 0x5d, 0xb0, 0x2f, 0xc7, 0x6f, 0xbc, 0x16,
	0xf6, 0xc0, 0x3d, 0x1b, 0xbf, 0x3b, 0xbf, 0xa0, 0xc0, 0xb3, 0x0d, 0x41, 0xa3, 0x60, 0x3c, 0x1d,
	0x79, 0xed, 0xd3, 0x57, 0xeb, 0x8d, 0xb4, 0xae, 0x37, 0xd2, 0xba, 0xd9, 0x48, 0xf1, 0xad, 0x92,
	0xe2, 0x67, 0x25, 0xc5, 0xaf, 0x4a, 0x8a, 0x75, 0x25, 0xc5, 0x9f, 0x4a, 0x8a, 0xbf, 0x95, 0xb4,
	0x6e, 0x2a, 0x29, 0x7e, 0x6c, 0xa5, 0xb5, 0xde, 0x4a, 0xeb, 0x7a, 0x2b, 0xad, 0x4f, 0x1d, 0x7e,
	0xb7, 0x2f, 0xff, 0x05, 0x00, 0x00, 0xff, 0xff, 0x48, 0x9e, 0xa6, 0x52, 0xc8, 0x02, 0x00, 0x00,
}

func (x MsgType) String() string {
	s, ok := MsgType_name[int32(x)]
	if ok {
		return s
	}
	return strconv.Itoa(int(x))
}
func (this *TotalMsg) Equal(that interface{}) bool {
	if that == nil {
		return this == nil
	}

	that1, ok := that.(*TotalMsg)
	if !ok {
		that2, ok := that.(TotalMsg)
		if ok {
			that1 = &that2
		} else {
			return false
		}
	}
	if that1 == nil {
		return this == nil
	} else if this == nil {
		return false
	}
	if this.Type != that1.Type {
		return false
	}
	if !this.Verify.Equal(that1.Verify) {
		return false
	}
	if !this.Log.Equal(that1.Log) {
		return false
	}
	if !this.Confirm.Equal(that1.Confirm) {
		return false
	}
	if !this.Remove.Equal(that1.Remove) {
		return false
	}
	return true
}
func (this *VerifyMsg) Equal(that interface{}) bool {
	if that == nil {
		return this == nil
	}

	that1, ok := that.(*VerifyMsg)
	if !ok {
		that2, ok := that.(VerifyMsg)
		if ok {
			that1 = &that2
		} else {
			return false
		}
	}
	if that1 == nil {
		return this == nil
	} else if this == nil {
		return false
	}
	return true
}
func (this *LogMsg) Equal(that interface{}) bool {
	if that == nil {
		return this == nil
	}

	that1, ok := that.(*LogMsg)
	if !ok {
		that2, ok := that.(LogMsg)
		if ok {
			that1 = &that2
		} else {
			return false
		}
	}
	if that1 == nil {
		return this == nil
	} else if this == nil {
		return false
	}
	if this.Serverid != that1.Serverid {
		return false
	}
	if !bytes.Equal(this.Content, that1.Content) {
		return false
	}
	if this.Filename != that1.Filename {
		return false
	}
	if this.Line != that1.Line {
		return false
	}
	if this.Memindex != that1.Memindex {
		return false
	}
	return true
}
func (this *ConfirmMsg) Equal(that interface{}) bool {
	if that == nil {
		return this == nil
	}

	that1, ok := that.(*ConfirmMsg)
	if !ok {
		that2, ok := that.(ConfirmMsg)
		if ok {
			that1 = &that2
		} else {
			return false
		}
	}
	if that1 == nil {
		return this == nil
	} else if this == nil {
		return false
	}
	if this.Filename != that1.Filename {
		return false
	}
	if this.Line != that1.Line {
		return false
	}
	if this.Memindex != that1.Memindex {
		return false
	}
	return true
}
func (this *RemoveMsg) Equal(that interface{}) bool {
	if that == nil {
		return this == nil
	}

	that1, ok := that.(*RemoveMsg)
	if !ok {
		that2, ok := that.(RemoveMsg)
		if ok {
			that1 = &that2
		} else {
			return false
		}
	}
	if that1 == nil {
		return this == nil
	} else if this == nil {
		return false
	}
	if this.Year != that1.Year {
		return false
	}
	if this.Month != that1.Month {
		return false
	}
	if this.Day != that1.Day {
		return false
	}
	if this.Hour != that1.Hour {
		return false
	}
	return true
}
func (this *TotalMsg) GoString() string {
	if this == nil {
		return "nil"
	}
	s := make([]string, 0, 9)
	s = append(s, "&nothing.TotalMsg{")
	s = append(s, "Type: "+fmt.Sprintf("%#v", this.Type)+",\n")
	if this.Verify != nil {
		s = append(s, "Verify: "+fmt.Sprintf("%#v", this.Verify)+",\n")
	}
	if this.Log != nil {
		s = append(s, "Log: "+fmt.Sprintf("%#v", this.Log)+",\n")
	}
	if this.Confirm != nil {
		s = append(s, "Confirm: "+fmt.Sprintf("%#v", this.Confirm)+",\n")
	}
	if this.Remove != nil {
		s = append(s, "Remove: "+fmt.Sprintf("%#v", this.Remove)+",\n")
	}
	s = append(s, "}")
	return strings.Join(s, "")
}
func (this *VerifyMsg) GoString() string {
	if this == nil {
		return "nil"
	}
	s := make([]string, 0, 4)
	s = append(s, "&nothing.VerifyMsg{")
	s = append(s, "}")
	return strings.Join(s, "")
}
func (this *LogMsg) GoString() string {
	if this == nil {
		return "nil"
	}
	s := make([]string, 0, 9)
	s = append(s, "&nothing.LogMsg{")
	s = append(s, "Serverid: "+fmt.Sprintf("%#v", this.Serverid)+",\n")
	s = append(s, "Content: "+fmt.Sprintf("%#v", this.Content)+",\n")
	s = append(s, "Filename: "+fmt.Sprintf("%#v", this.Filename)+",\n")
	s = append(s, "Line: "+fmt.Sprintf("%#v", this.Line)+",\n")
	s = append(s, "Memindex: "+fmt.Sprintf("%#v", this.Memindex)+",\n")
	s = append(s, "}")
	return strings.Join(s, "")
}
func (this *ConfirmMsg) GoString() string {
	if this == nil {
		return "nil"
	}
	s := make([]string, 0, 7)
	s = append(s, "&nothing.ConfirmMsg{")
	s = append(s, "Filename: "+fmt.Sprintf("%#v", this.Filename)+",\n")
	s = append(s, "Line: "+fmt.Sprintf("%#v", this.Line)+",\n")
	s = append(s, "Memindex: "+fmt.Sprintf("%#v", this.Memindex)+",\n")
	s = append(s, "}")
	return strings.Join(s, "")
}
func (this *RemoveMsg) GoString() string {
	if this == nil {
		return "nil"
	}
	s := make([]string, 0, 8)
	s = append(s, "&nothing.RemoveMsg{")
	s = append(s, "Year: "+fmt.Sprintf("%#v", this.Year)+",\n")
	s = append(s, "Month: "+fmt.Sprintf("%#v", this.Month)+",\n")
	s = append(s, "Day: "+fmt.Sprintf("%#v", this.Day)+",\n")
	s = append(s, "Hour: "+fmt.Sprintf("%#v", this.Hour)+",\n")
	s = append(s, "}")
	return strings.Join(s, "")
}
func valueToGoStringMessage(v interface{}, typ string) string {
	rv := reflect.ValueOf(v)
	if rv.IsNil() {
		return "nil"
	}
	pv := reflect.Indirect(rv).Interface()
	return fmt.Sprintf("func(v %v) *%v { return &v } ( %#v )", typ, typ, pv)
}
func (m *TotalMsg) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalTo(dAtA)
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *TotalMsg) MarshalTo(dAtA []byte) (int, error) {
	var i int
	_ = i
	var l int
	_ = l
	if m.Type != 0 {
		dAtA[i] = 0x8
		i++
		i = encodeVarintMessage(dAtA, i, uint64(m.Type))
	}
	if m.Verify != nil {
		dAtA[i] = 0x12
		i++
		i = encodeVarintMessage(dAtA, i, uint64(m.Verify.Size()))
		n1, err1 := m.Verify.MarshalTo(dAtA[i:])
		if err1 != nil {
			return 0, err1
		}
		i += n1
	}
	if m.Log != nil {
		dAtA[i] = 0x1a
		i++
		i = encodeVarintMessage(dAtA, i, uint64(m.Log.Size()))
		n2, err2 := m.Log.MarshalTo(dAtA[i:])
		if err2 != nil {
			return 0, err2
		}
		i += n2
	}
	if m.Confirm != nil {
		dAtA[i] = 0x22
		i++
		i = encodeVarintMessage(dAtA, i, uint64(m.Confirm.Size()))
		n3, err3 := m.Confirm.MarshalTo(dAtA[i:])
		if err3 != nil {
			return 0, err3
		}
		i += n3
	}
	if m.Remove != nil {
		dAtA[i] = 0x2a
		i++
		i = encodeVarintMessage(dAtA, i, uint64(m.Remove.Size()))
		n4, err4 := m.Remove.MarshalTo(dAtA[i:])
		if err4 != nil {
			return 0, err4
		}
		i += n4
	}
	return i, nil
}

func (m *VerifyMsg) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalTo(dAtA)
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *VerifyMsg) MarshalTo(dAtA []byte) (int, error) {
	var i int
	_ = i
	var l int
	_ = l
	return i, nil
}

func (m *LogMsg) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalTo(dAtA)
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *LogMsg) MarshalTo(dAtA []byte) (int, error) {
	var i int
	_ = i
	var l int
	_ = l
	if m.Serverid != 0 {
		dAtA[i] = 0x8
		i++
		i = encodeVarintMessage(dAtA, i, uint64(m.Serverid))
	}
	if len(m.Content) > 0 {
		dAtA[i] = 0x12
		i++
		i = encodeVarintMessage(dAtA, i, uint64(len(m.Content)))
		i += copy(dAtA[i:], m.Content)
	}
	if len(m.Filename) > 0 {
		dAtA[i] = 0x1a
		i++
		i = encodeVarintMessage(dAtA, i, uint64(len(m.Filename)))
		i += copy(dAtA[i:], m.Filename)
	}
	if m.Line != 0 {
		dAtA[i] = 0x20
		i++
		i = encodeVarintMessage(dAtA, i, uint64(m.Line))
	}
	if m.Memindex != 0 {
		dAtA[i] = 0x28
		i++
		i = encodeVarintMessage(dAtA, i, uint64(m.Memindex))
	}
	return i, nil
}

func (m *ConfirmMsg) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalTo(dAtA)
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *ConfirmMsg) MarshalTo(dAtA []byte) (int, error) {
	var i int
	_ = i
	var l int
	_ = l
	if len(m.Filename) > 0 {
		dAtA[i] = 0xa
		i++
		i = encodeVarintMessage(dAtA, i, uint64(len(m.Filename)))
		i += copy(dAtA[i:], m.Filename)
	}
	if m.Line != 0 {
		dAtA[i] = 0x10
		i++
		i = encodeVarintMessage(dAtA, i, uint64(m.Line))
	}
	if m.Memindex != 0 {
		dAtA[i] = 0x18
		i++
		i = encodeVarintMessage(dAtA, i, uint64(m.Memindex))
	}
	return i, nil
}

func (m *RemoveMsg) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalTo(dAtA)
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *RemoveMsg) MarshalTo(dAtA []byte) (int, error) {
	var i int
	_ = i
	var l int
	_ = l
	if m.Year != 0 {
		dAtA[i] = 0x8
		i++
		i = encodeVarintMessage(dAtA, i, uint64(m.Year))
	}
	if m.Month != 0 {
		dAtA[i] = 0x10
		i++
		i = encodeVarintMessage(dAtA, i, uint64(m.Month))
	}
	if m.Day != 0 {
		dAtA[i] = 0x18
		i++
		i = encodeVarintMessage(dAtA, i, uint64(m.Day))
	}
	if m.Hour != 0 {
		dAtA[i] = 0x20
		i++
		i = encodeVarintMessage(dAtA, i, uint64(m.Hour))
	}
	return i, nil
}

func encodeVarintMessage(dAtA []byte, offset int, v uint64) int {
	for v >= 1<<7 {
		dAtA[offset] = uint8(v&0x7f | 0x80)
		v >>= 7
		offset++
	}
	dAtA[offset] = uint8(v)
	return offset + 1
}
func (m *TotalMsg) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	if m.Type != 0 {
		n += 1 + sovMessage(uint64(m.Type))
	}
	if m.Verify != nil {
		l = m.Verify.Size()
		n += 1 + l + sovMessage(uint64(l))
	}
	if m.Log != nil {
		l = m.Log.Size()
		n += 1 + l + sovMessage(uint64(l))
	}
	if m.Confirm != nil {
		l = m.Confirm.Size()
		n += 1 + l + sovMessage(uint64(l))
	}
	if m.Remove != nil {
		l = m.Remove.Size()
		n += 1 + l + sovMessage(uint64(l))
	}
	return n
}

func (m *VerifyMsg) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	return n
}

func (m *LogMsg) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	if m.Serverid != 0 {
		n += 1 + sovMessage(uint64(m.Serverid))
	}
	l = len(m.Content)
	if l > 0 {
		n += 1 + l + sovMessage(uint64(l))
	}
	l = len(m.Filename)
	if l > 0 {
		n += 1 + l + sovMessage(uint64(l))
	}
	if m.Line != 0 {
		n += 1 + sovMessage(uint64(m.Line))
	}
	if m.Memindex != 0 {
		n += 1 + sovMessage(uint64(m.Memindex))
	}
	return n
}

func (m *ConfirmMsg) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	l = len(m.Filename)
	if l > 0 {
		n += 1 + l + sovMessage(uint64(l))
	}
	if m.Line != 0 {
		n += 1 + sovMessage(uint64(m.Line))
	}
	if m.Memindex != 0 {
		n += 1 + sovMessage(uint64(m.Memindex))
	}
	return n
}

func (m *RemoveMsg) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	if m.Year != 0 {
		n += 1 + sovMessage(uint64(m.Year))
	}
	if m.Month != 0 {
		n += 1 + sovMessage(uint64(m.Month))
	}
	if m.Day != 0 {
		n += 1 + sovMessage(uint64(m.Day))
	}
	if m.Hour != 0 {
		n += 1 + sovMessage(uint64(m.Hour))
	}
	return n
}

func sovMessage(x uint64) (n int) {
	return (math_bits.Len64(x|1) + 6) / 7
}
func sozMessage(x uint64) (n int) {
	return sovMessage(uint64((x << 1) ^ uint64((int64(x) >> 63))))
}
func (this *TotalMsg) String() string {
	if this == nil {
		return "nil"
	}
	s := strings.Join([]string{`&TotalMsg{`,
		`Type:` + fmt.Sprintf("%v", this.Type) + `,`,
		`Verify:` + strings.Replace(this.Verify.String(), "VerifyMsg", "VerifyMsg", 1) + `,`,
		`Log:` + strings.Replace(this.Log.String(), "LogMsg", "LogMsg", 1) + `,`,
		`Confirm:` + strings.Replace(this.Confirm.String(), "ConfirmMsg", "ConfirmMsg", 1) + `,`,
		`Remove:` + strings.Replace(this.Remove.String(), "RemoveMsg", "RemoveMsg", 1) + `,`,
		`}`,
	}, "")
	return s
}
func (this *VerifyMsg) String() string {
	if this == nil {
		return "nil"
	}
	s := strings.Join([]string{`&VerifyMsg{`,
		`}`,
	}, "")
	return s
}
func (this *LogMsg) String() string {
	if this == nil {
		return "nil"
	}
	s := strings.Join([]string{`&LogMsg{`,
		`Serverid:` + fmt.Sprintf("%v", this.Serverid) + `,`,
		`Content:` + fmt.Sprintf("%v", this.Content) + `,`,
		`Filename:` + fmt.Sprintf("%v", this.Filename) + `,`,
		`Line:` + fmt.Sprintf("%v", this.Line) + `,`,
		`Memindex:` + fmt.Sprintf("%v", this.Memindex) + `,`,
		`}`,
	}, "")
	return s
}
func (this *ConfirmMsg) String() string {
	if this == nil {
		return "nil"
	}
	s := strings.Join([]string{`&ConfirmMsg{`,
		`Filename:` + fmt.Sprintf("%v", this.Filename) + `,`,
		`Line:` + fmt.Sprintf("%v", this.Line) + `,`,
		`Memindex:` + fmt.Sprintf("%v", this.Memindex) + `,`,
		`}`,
	}, "")
	return s
}
func (this *RemoveMsg) String() string {
	if this == nil {
		return "nil"
	}
	s := strings.Join([]string{`&RemoveMsg{`,
		`Year:` + fmt.Sprintf("%v", this.Year) + `,`,
		`Month:` + fmt.Sprintf("%v", this.Month) + `,`,
		`Day:` + fmt.Sprintf("%v", this.Day) + `,`,
		`Hour:` + fmt.Sprintf("%v", this.Hour) + `,`,
		`}`,
	}, "")
	return s
}
func valueToStringMessage(v interface{}) string {
	rv := reflect.ValueOf(v)
	if rv.IsNil() {
		return "nil"
	}
	pv := reflect.Indirect(rv).Interface()
	return fmt.Sprintf("*%v", pv)
}
func (m *TotalMsg) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowMessage
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: TotalMsg: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: TotalMsg: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field Type", wireType)
			}
			m.Type = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowMessage
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.Type |= MsgType(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		case 2:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Verify", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowMessage
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthMessage
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthMessage
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			if m.Verify == nil {
				m.Verify = &VerifyMsg{}
			}
			if err := m.Verify.Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		case 3:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Log", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowMessage
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthMessage
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthMessage
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			if m.Log == nil {
				m.Log = &LogMsg{}
			}
			if err := m.Log.Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		case 4:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Confirm", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowMessage
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthMessage
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthMessage
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			if m.Confirm == nil {
				m.Confirm = &ConfirmMsg{}
			}
			if err := m.Confirm.Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		case 5:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Remove", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowMessage
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthMessage
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthMessage
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			if m.Remove == nil {
				m.Remove = &RemoveMsg{}
			}
			if err := m.Remove.Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		default:
			iNdEx = preIndex
			skippy, err := skipMessage(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if skippy < 0 {
				return ErrInvalidLengthMessage
			}
			if (iNdEx + skippy) < 0 {
				return ErrInvalidLengthMessage
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *VerifyMsg) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowMessage
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: VerifyMsg: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: VerifyMsg: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		default:
			iNdEx = preIndex
			skippy, err := skipMessage(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if skippy < 0 {
				return ErrInvalidLengthMessage
			}
			if (iNdEx + skippy) < 0 {
				return ErrInvalidLengthMessage
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *LogMsg) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowMessage
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: LogMsg: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: LogMsg: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field Serverid", wireType)
			}
			m.Serverid = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowMessage
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.Serverid |= int64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		case 2:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Content", wireType)
			}
			var byteLen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowMessage
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				byteLen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if byteLen < 0 {
				return ErrInvalidLengthMessage
			}
			postIndex := iNdEx + byteLen
			if postIndex < 0 {
				return ErrInvalidLengthMessage
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Content = append(m.Content[:0], dAtA[iNdEx:postIndex]...)
			if m.Content == nil {
				m.Content = []byte{}
			}
			iNdEx = postIndex
		case 3:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Filename", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowMessage
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthMessage
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthMessage
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Filename = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 4:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field Line", wireType)
			}
			m.Line = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowMessage
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.Line |= uint32(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		case 5:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field Memindex", wireType)
			}
			m.Memindex = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowMessage
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.Memindex |= uint32(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		default:
			iNdEx = preIndex
			skippy, err := skipMessage(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if skippy < 0 {
				return ErrInvalidLengthMessage
			}
			if (iNdEx + skippy) < 0 {
				return ErrInvalidLengthMessage
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *ConfirmMsg) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowMessage
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: ConfirmMsg: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: ConfirmMsg: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Filename", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowMessage
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthMessage
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthMessage
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Filename = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 2:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field Line", wireType)
			}
			m.Line = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowMessage
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.Line |= uint32(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		case 3:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field Memindex", wireType)
			}
			m.Memindex = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowMessage
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.Memindex |= uint32(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		default:
			iNdEx = preIndex
			skippy, err := skipMessage(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if skippy < 0 {
				return ErrInvalidLengthMessage
			}
			if (iNdEx + skippy) < 0 {
				return ErrInvalidLengthMessage
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *RemoveMsg) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowMessage
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: RemoveMsg: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: RemoveMsg: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field Year", wireType)
			}
			m.Year = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowMessage
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.Year |= int32(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		case 2:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field Month", wireType)
			}
			m.Month = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowMessage
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.Month |= int32(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		case 3:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field Day", wireType)
			}
			m.Day = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowMessage
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.Day |= int32(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		case 4:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field Hour", wireType)
			}
			m.Hour = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowMessage
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.Hour |= int32(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		default:
			iNdEx = preIndex
			skippy, err := skipMessage(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if skippy < 0 {
				return ErrInvalidLengthMessage
			}
			if (iNdEx + skippy) < 0 {
				return ErrInvalidLengthMessage
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func skipMessage(dAtA []byte) (n int, err error) {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return 0, ErrIntOverflowMessage
			}
			if iNdEx >= l {
				return 0, io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= (uint64(b) & 0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		wireType := int(wire & 0x7)
		switch wireType {
		case 0:
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return 0, ErrIntOverflowMessage
				}
				if iNdEx >= l {
					return 0, io.ErrUnexpectedEOF
				}
				iNdEx++
				if dAtA[iNdEx-1] < 0x80 {
					break
				}
			}
			return iNdEx, nil
		case 1:
			iNdEx += 8
			return iNdEx, nil
		case 2:
			var length int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return 0, ErrIntOverflowMessage
				}
				if iNdEx >= l {
					return 0, io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				length |= (int(b) & 0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if length < 0 {
				return 0, ErrInvalidLengthMessage
			}
			iNdEx += length
			if iNdEx < 0 {
				return 0, ErrInvalidLengthMessage
			}
			return iNdEx, nil
		case 3:
			for {
				var innerWire uint64
				var start int = iNdEx
				for shift := uint(0); ; shift += 7 {
					if shift >= 64 {
						return 0, ErrIntOverflowMessage
					}
					if iNdEx >= l {
						return 0, io.ErrUnexpectedEOF
					}
					b := dAtA[iNdEx]
					iNdEx++
					innerWire |= (uint64(b) & 0x7F) << shift
					if b < 0x80 {
						break
					}
				}
				innerWireType := int(innerWire & 0x7)
				if innerWireType == 4 {
					break
				}
				next, err := skipMessage(dAtA[start:])
				if err != nil {
					return 0, err
				}
				iNdEx = start + next
				if iNdEx < 0 {
					return 0, ErrInvalidLengthMessage
				}
			}
			return iNdEx, nil
		case 4:
			return iNdEx, nil
		case 5:
			iNdEx += 4
			return iNdEx, nil
		default:
			return 0, fmt.Errorf("proto: illegal wireType %d", wireType)
		}
	}
	panic("unreachable")
}

var (
	ErrInvalidLengthMessage = fmt.Errorf("proto: negative length found during unmarshaling")
	ErrIntOverflowMessage   = fmt.Errorf("proto: integer overflow")
)
