package country

var CountryName = []string{"Afghanistan", "Albania", "Algeria", "America", "Angola", "Argentina", "Armenia", "Australia", "Austria", "Azerbaijan", "Bahamas", "Bangladesh", "Belarus", "Belgium", "Belize", "Benin", "Bolivia", "Bosnia and Herzegovina", "Botswana", "Brazil", "Brunei", "Bulgaria", "Burkina Faso", "Burundi", "Cambodia", "Cameroon", "Canada", "Central African Republic", "Chad", "Chile", "China", "Colombia", "Congo Democratic Republic", "Congo Republic", "CostaRica", "Cote Divoire", "Croatia", "Cuba", "Czech Republic", "Denmark", "Djibouti", "Dominican Republic", "Ecuador", "Egypt", "El Salvador", "Equatorial Guinea", "Eritrea", "Estonia", "Ethiopia", "Finland", "France", "Gabon", "Gambia", "Georgia Country", "Germany", "Ghana", "Greece", "Guatemala", "Guinea", "Guinea Bissau", "Guyana", "Haiti", "Honduras", "Hungary", "Iceland", "India", "Indonesia", "Iran", "Iraq", "Ireland", "Israel", "Italy", "Jamaica", "Japan", "Jordan", "Kazakhstan", "Kenya", "Kyrgyzstan", "Laos", "Latvia", "Lebanon", "Lesotho", "Liberia", "Libya", "Lithuania", "Macedonia", "Malawi", "Malaysia", "Maldives", "Mali", "Mauritania", "Mexico", "Moldova", "Montenegro", "Morocco", "Mozambique", "Myanmar", "Namibia", "Nepal", "Netherlands", "New Zealand", "Nicaragua", "Niger", "Nigeria", "Norway", "Oman", "Pakistan", "Panama", "Papua New Guinea", "Paraguay", "Peru", "Philippines", "Poland", "Portugal", "Romania", "Russia", "Rwanda", "Saudi Arabia", "Senegal", "Serbia", "Sierra Leone", "Singapore", "Slovakia", "Slovenia", "Somalia", "South Africa", "South Korea", "Spain", "Sri Lanka", "Sudan", "Suriname", "Swaziland", "Sweden", "Switzerland", "Syria", "Tajikistan", "Tanzania", "Thailand", "Togo", "Tunisia", "Turkey", "Turkmenistan", "Uganda", "Ukraine", "United Arab Emirates", "United Kingdom", "Uruguay", "Uzbekistan", "Venezuela", "Vietnam", "Western Sahara", "Yemen", "Zambia", "Zimbabwe"}
var CountryCode = map[string]string{
	"China":                     "CN",
	"Russia":                    "RU",
	"America":                   "US",
	"Canada":                    "CA",
	"Vietnam":                   "VN",
	"Laos":                      "LA",
	"Myanmar":                   "MM",
	"Nepal":                     "NP",
	"Cambodia":                  "KH",
	"Thailand":                  "TH",
	"Bangladesh":                "BD",
	"India":                     "IN",
	"Malaysia":                  "MY",
	"Singapore":                 "SG",
	"Brunei":                    "BN",
	"Indonesia":                 "ID",
	"Sri Lanka":                 "LK",
	"Maldives":                  "MV",
	"Philippines":               "PH",
	"Papua New Guinea":          "PG",
	"Australia":                 "AU",
	"New Zealand":               "NZ",
	"South Korea":               "KR",
	"Japan":                     "JP",
	"Pakistan":                  "PK",
	"Mexico":                    "MX",
	"Afghanistan":               "AF",
	"Iran":                      "IR",
	"Kazakhstan":                "KZ",
	"Uzbekistan":                "UZ",
	"Turkmenistan":              "TM",
	"Kyrgyzstan":                "KG",
	"Tajikistan":                "TJ",
	"Turkey":                    "TR",
	"Iraq":                      "IQ",
	"Saudi Arabia":              "SA",
	"United Arab Emirates":      "AE",
	"Oman":                      "OM",
	"Yemen":                     "YE",
	"Jordan":                    "JO",
	"Georgia Country":           "GE",
	"Armenia":                   "AM",
	"Azerbaijan":                "AZ",
	"Finland":                   "FI",
	"Sweden":                    "SE",
	"Norway":                    "NO",
	"Estonia":                   "EE",
	"Latvia":                    "LV",
	"Lithuania":                 "LT",
	"Belarus":                   "BY",
	"Ukraine":                   "UA",
	"Moldova":                   "MD",
	"Syria":                     "SY",
	"Lebanon":                   "LB",
	"Israel":                    "IL",
	"Romania":                   "RO",
	"Bulgaria":                  "BG",
	"Greece":                    "GR",
	"Poland":                    "PL",
	"Czech Republic":            "CZ",
	"Slovakia":                  "SK",
	"Austria":                   "AT",
	"Hungary":                   "HU",
	"Slovenia":                  "SI",
	"Croatia":                   "HR",
	"Bosnia and Herzegovina":    "BA",
	"Montenegro":                "ME",
	"Albania":                   "AL",
	"Macedonia":                 "MK",
	"Serbia":                    "RS",
	"Italy":                     "IT",
	"Switzerland":               "CH",
	"Germany":                   "DE",
	"Denmark":                   "DK",
	"Netherlands":               "NL",
	"Belgium":                   "BE",
	"United Kingdom":            "GB",
	"Ireland":                   "IE",
	"France":                    "FR",
	"Spain":                     "ES",
	"Portugal":                  "PT",
	"Iceland":                   "IS",
	"Egypt":                     "EG",
	"Libya":                     "LY",
	"Tunisia":                   "TN",
	"Algeria":                   "DZ",
	"Morocco":                   "MA",
	"Western Sahara":            "EH",
	"Mauritania":                "MR",
	"Mali":                      "ML",
	"Niger":                     "NE",
	"Chad":                      "TD",
	"Senegal":                   "SN",
	"Gambia":                    "GM",
	"Guinea Bissau":             "GW",
	"Guinea":                    "GN",
	"Sierra Leone":              "SL",
	"Liberia":                   "LR",
	"Burkina Faso":              "BF",
	"Cote Divoire":              "CI",
	"Ghana":                     "GH",
	"Togo":                      "TG",
	"Benin":                     "BJ",
	"Nigeria":                   "NG",
	"Cameroon":                  "CM",
	"Central African Republic":  "CF",
	"Sudan":                     "SD",
	"Eritrea":                   "ER",
	"Ethiopia":                  "ET",
	"Djibouti":                  "DJ",
	"Somalia":                   "SO",
	"Kenya":                     "KE",
	"Uganda":                    "UG",
	"Rwanda":                    "RW",
	"Burundi":                   "BI",
	"Tanzania":                  "TZ",
	"Equatorial Guinea":         "GQ",
	"Gabon":                     "GA",
	"Angola":                    "AO",
	"Congo Republic":            "CG",
	"Congo Democratic Republic": "CD",
	"Zambia":                    "ZM",
	"Malawi":                    "MW",
	"Mozambique":                "MZ",
	"Zimbabwe":                  "ZW",
	"Botswana":                  "BW",
	"Namibia":                   "NA",
	"Lesotho":                   "LS",
	"Swaziland":                 "SZ",
	"South Africa":              "ZA",
	"Chile":                     "CL",
	"Argentina":                 "AR",
	"Uruguay":                   "UY",
	"Paraguay":                  "PY",
	"Bolivia":                   "BO",
	"Brazil":                    "BR",
	"Peru":                      "PE",
	"Ecuador":                   "EC",
	"Colombia":                  "CO",
	"Venezuela":                 "VE",
	"Guyana":                    "GY",
	"Suriname":                  "SR",
	"Panama":                    "PA",
	"Costa Rica":                "CR",
	"Nicaragua":                 "NI",
	"Honduras":                  "HN",
	"El Salvador":               "SV",
	"Guatemala":                 "GT",
	"Belize":                    "BZ",
	"Cuba":                      "CU",
	"Haiti":                     "HT",
	"Bahamas":                   "BS",
	"Jamaica":                   "JM",
	"Dominican Republic":        "DO",
}
var CountryTelPrefix = map[string]string{
	"China":                     "86",
	"Russia":                    "7",
	"America":                   "1",
	"Canada":                    "1",
	"Vietnam":                   "84",
	"Laos":                      "856",
	"Myanmar":                   "95",
	"Nepal":                     "977",
	"Cambodia":                  "855",
	"Thailand":                  "66",
	"Bangladesh":                "880",
	"India":                     "91",
	"Malaysia":                  "60",
	"Singapore":                 "65",
	"Brunei":                    "673",
	"Indonesia":                 "62",
	"Sri Lanka":                 "94",
	"Maldives":                  "960",
	"Philippines":               "63",
	"Papua New Guinea":          "675",
	"Australia":                 "61",
	"New Zealand":               "64",
	"South Korea":               "82",
	"Japan":                     "81",
	"Pakistan":                  "92",
	"Mexico":                    "52",
	"Afghanistan":               "93",
	"Iran":                      "98",
	"Kazakhstan":                "997",
	"Uzbekistan":                "998",
	"Turkmenistan":              "993",
	"Kyrgyzstan":                "995",
	"Tajikistan":                "992",
	"Turkey":                    "90",
	"Iraq":                      "964",
	"Saudi Arabia":              "966",
	"United Arab Emirates":      "971",
	"Oman":                      "968",
	"Yemen":                     "967",
	"Jordan":                    "962",
	"Georgia Country":           "995",
	"Armenia":                   "374",
	"Azerbaijan":                "994",
	"Finland":                   "358",
	"Sweden":                    "46",
	"Norway":                    "47",
	"Estonia":                   "372",
	"Latvia":                    "371",
	"Lithuania":                 "370",
	"Belarus":                   "375",
	"Ukraine":                   "380",
	"Moldova":                   "373",
	"Syria":                     "963",
	"Lebanon":                   "961",
	"Israel":                    "972",
	"Romania":                   "40",
	"Bulgaria":                  "359",
	"Greece":                    "30",
	"Poland":                    "48",
	"Czech Republic":            "420",
	"Slovakia":                  "421",
	"Austria":                   "43",
	"Hungary":                   "36",
	"Slovenia":                  "386",
	"Croatia":                   "385",
	"Bosnia and Herzegovina":    "387",
	"Montenegro":                "382",
	"Albania":                   "355",
	"Macedonia":                 "389",
	"Serbia":                    "381",
	"Italy":                     "39",
	"Switzerland":               "41",
	"Germany":                   "49",
	"Denmark":                   "45",
	"Netherlands":               "31",
	"Belgium":                   "32",
	"United Kingdom":            "44",
	"Ireland":                   "353",
	"France":                    "33",
	"Spain":                     "34",
	"Portugal":                  "351",
	"Iceland":                   "354",
	"Egypt":                     "20",
	"Libya":                     "218",
	"Tunisia":                   "216",
	"Algeria":                   "213",
	"Morocco":                   "212",
	"Western Sahara":            "210",
	"Mauritania":                "222",
	"Mali":                      "223",
	"Niger":                     "227",
	"Chad":                      "235",
	"Senegal":                   "221",
	"Gambia":                    "220",
	"Guinea Bissau":             "245",
	"Guinea":                    "224",
	"Sierra Leone":              "232",
	"Liberia":                   "231",
	"Burkina Faso":              "226",
	"Cote Divoire":              "225",
	"Ghana":                     "233",
	"Togo":                      "228",
	"Benin":                     "229",
	"Nigeria":                   "234",
	"Cameroon":                  "237",
	"Central African Republic":  "236",
	"Sudan":                     "249",
	"Eritrea":                   "291",
	"Ethiopia":                  "251",
	"Djibouti":                  "253",
	"Somalia":                   "252",
	"Kenya":                     "254",
	"Uganda":                    "256",
	"Rwanda":                    "250",
	"Burundi":                   "257",
	"Tanzania":                  "255",
	"Equatorial Guinea":         "240",
	"Gabon":                     "241",
	"Angola":                    "244",
	"Congo Republic":            "242",
	"Congo Democratic Republic": "243",
	"Zambia":                    "260",
	"Malawi":                    "265",
	"Mozambique":                "258",
	"Zimbabwe":                  "263",
	"Botswana":                  "267",
	"Namibia":                   "264",
	"Eswatini":                  "268",
	"Lesotho":                   "266",
	"Swaziland":                 "268",
	"South Africa":              "27",
	"Chile":                     "56",
	"Argentina":                 "54",
	"Uruguay":                   "598",
	"Paraguay":                  "595",
	"Bolivia":                   "591",
	"Brazil":                    "55",
	"Peru":                      "51",
	"Ecuador":                   "593",
	"Colombia":                  "57",
	"Venezuela":                 "58",
	"Guyana":                    "592",
	"Suriname":                  "597",
	"Panama":                    "507",
	"Costa Rica":                "506",
	"Nicaragua":                 "505",
	"Honduras":                  "504",
	"El Salvador":               "503",
	"Guatemala":                 "502",
	"Belize":                    "501",
	"Cuba":                      "53",
	"Haiti":                     "509",
	"Bahamas":                   "1242",
	"Jamaica":                   "1876",
	"Dominican Republic":        "1809",
}
