// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.25.0
// 	protoc        v3.12.4
// source: protoc-gen-go-web/first/first.proto

package first

import (
	proto "github.com/golang/protobuf/proto"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	second "protoc-gen-go-web/second"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// This is a compile-time assertion that a sufficiently up-to-date version
// of the legacy proto package is being used.
const _ = proto.ProtoPackageIsVersion4

type HelloReq struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Name string `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	Sex  int64  `protobuf:"varint,2,opt,name=sex,proto3" json:"sex,omitempty"`
	Addr string `protobuf:"bytes,3,opt,name=addr,proto3" json:"addr,omitempty"`
	Tel  string `protobuf:"bytes,4,opt,name=tel,proto3" json:"tel,omitempty"`
}

func (x *HelloReq) Reset() {
	*x = HelloReq{}
	if protoimpl.UnsafeEnabled {
		mi := &file_protoc_gen_go_web_first_first_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *HelloReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*HelloReq) ProtoMessage() {}

func (x *HelloReq) ProtoReflect() protoreflect.Message {
	mi := &file_protoc_gen_go_web_first_first_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use HelloReq.ProtoReflect.Descriptor instead.
func (*HelloReq) Descriptor() ([]byte, []int) {
	return file_protoc_gen_go_web_first_first_proto_rawDescGZIP(), []int{0}
}

func (x *HelloReq) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *HelloReq) GetSex() int64 {
	if x != nil {
		return x.Sex
	}
	return 0
}

func (x *HelloReq) GetAddr() string {
	if x != nil {
		return x.Addr
	}
	return ""
}

func (x *HelloReq) GetTel() string {
	if x != nil {
		return x.Tel
	}
	return ""
}

type HelloResp struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Name string `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	Sex  int64  `protobuf:"varint,2,opt,name=sex,proto3" json:"sex,omitempty"`
	Addr string `protobuf:"bytes,3,opt,name=addr,proto3" json:"addr,omitempty"`
	Tel  string `protobuf:"bytes,4,opt,name=tel,proto3" json:"tel,omitempty"`
}

func (x *HelloResp) Reset() {
	*x = HelloResp{}
	if protoimpl.UnsafeEnabled {
		mi := &file_protoc_gen_go_web_first_first_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *HelloResp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*HelloResp) ProtoMessage() {}

func (x *HelloResp) ProtoReflect() protoreflect.Message {
	mi := &file_protoc_gen_go_web_first_first_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use HelloResp.ProtoReflect.Descriptor instead.
func (*HelloResp) Descriptor() ([]byte, []int) {
	return file_protoc_gen_go_web_first_first_proto_rawDescGZIP(), []int{1}
}

func (x *HelloResp) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *HelloResp) GetSex() int64 {
	if x != nil {
		return x.Sex
	}
	return 0
}

func (x *HelloResp) GetAddr() string {
	if x != nil {
		return x.Addr
	}
	return ""
}

func (x *HelloResp) GetTel() string {
	if x != nil {
		return x.Tel
	}
	return ""
}

var File_protoc_gen_go_web_first_first_proto protoreflect.FileDescriptor

var file_protoc_gen_go_web_first_first_proto_rawDesc = []byte{
	0x0a, 0x23, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x63, 0x2d, 0x67, 0x65, 0x6e, 0x2d, 0x67, 0x6f, 0x2d,
	0x77, 0x65, 0x62, 0x2f, 0x66, 0x69, 0x72, 0x73, 0x74, 0x2f, 0x66, 0x69, 0x72, 0x73, 0x74, 0x2e,
	0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x05, 0x66, 0x69, 0x72, 0x73, 0x74, 0x1a, 0x25, 0x70, 0x72,
	0x6f, 0x74, 0x6f, 0x63, 0x2d, 0x67, 0x65, 0x6e, 0x2d, 0x67, 0x6f, 0x2d, 0x77, 0x65, 0x62, 0x2f,
	0x73, 0x65, 0x63, 0x6f, 0x6e, 0x64, 0x2f, 0x73, 0x65, 0x63, 0x6f, 0x6e, 0x64, 0x2e, 0x70, 0x72,
	0x6f, 0x74, 0x6f, 0x22, 0x57, 0x0a, 0x09, 0x68, 0x65, 0x6c, 0x6c, 0x6f, 0x5f, 0x72, 0x65, 0x71,
	0x12, 0x12, 0x0a, 0x04, 0x6e, 0x61, 0x6d, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04,
	0x6e, 0x61, 0x6d, 0x65, 0x12, 0x10, 0x0a, 0x03, 0x73, 0x65, 0x78, 0x18, 0x02, 0x20, 0x01, 0x28,
	0x03, 0x52, 0x03, 0x73, 0x65, 0x78, 0x12, 0x12, 0x0a, 0x04, 0x61, 0x64, 0x64, 0x72, 0x18, 0x03,
	0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x61, 0x64, 0x64, 0x72, 0x12, 0x10, 0x0a, 0x03, 0x74, 0x65,
	0x6c, 0x18, 0x04, 0x20, 0x01, 0x28, 0x09, 0x52, 0x03, 0x74, 0x65, 0x6c, 0x22, 0x58, 0x0a, 0x0a,
	0x68, 0x65, 0x6c, 0x6c, 0x6f, 0x5f, 0x72, 0x65, 0x73, 0x70, 0x12, 0x12, 0x0a, 0x04, 0x6e, 0x61,
	0x6d, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x6e, 0x61, 0x6d, 0x65, 0x12, 0x10,
	0x0a, 0x03, 0x73, 0x65, 0x78, 0x18, 0x02, 0x20, 0x01, 0x28, 0x03, 0x52, 0x03, 0x73, 0x65, 0x78,
	0x12, 0x12, 0x0a, 0x04, 0x61, 0x64, 0x64, 0x72, 0x18, 0x03, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04,
	0x61, 0x64, 0x64, 0x72, 0x12, 0x10, 0x0a, 0x03, 0x74, 0x65, 0x6c, 0x18, 0x04, 0x20, 0x01, 0x28,
	0x09, 0x52, 0x03, 0x74, 0x65, 0x6c, 0x32, 0x8b, 0x01, 0x0a, 0x04, 0x74, 0x65, 0x73, 0x74, 0x12,
	0x2c, 0x0a, 0x05, 0x68, 0x65, 0x6c, 0x6c, 0x6f, 0x12, 0x10, 0x2e, 0x66, 0x69, 0x72, 0x73, 0x74,
	0x2e, 0x68, 0x65, 0x6c, 0x6c, 0x6f, 0x5f, 0x72, 0x65, 0x71, 0x1a, 0x11, 0x2e, 0x66, 0x69, 0x72,
	0x73, 0x74, 0x2e, 0x68, 0x65, 0x6c, 0x6c, 0x6f, 0x5f, 0x72, 0x65, 0x73, 0x70, 0x12, 0x2b, 0x0a,
	0x04, 0x6b, 0x69, 0x73, 0x73, 0x12, 0x10, 0x2e, 0x73, 0x65, 0x63, 0x6f, 0x6e, 0x64, 0x2e, 0x6b,
	0x69, 0x73, 0x73, 0x5f, 0x72, 0x65, 0x71, 0x1a, 0x11, 0x2e, 0x73, 0x65, 0x63, 0x6f, 0x6e, 0x64,
	0x2e, 0x6b, 0x69, 0x73, 0x73, 0x5f, 0x72, 0x65, 0x73, 0x70, 0x12, 0x28, 0x0a, 0x03, 0x62, 0x79,
	0x65, 0x12, 0x0f, 0x2e, 0x73, 0x65, 0x63, 0x6f, 0x6e, 0x64, 0x2e, 0x62, 0x79, 0x65, 0x5f, 0x72,
	0x65, 0x71, 0x1a, 0x10, 0x2e, 0x73, 0x65, 0x63, 0x6f, 0x6e, 0x64, 0x2e, 0x62, 0x79, 0x65, 0x5f,
	0x72, 0x65, 0x73, 0x70, 0x42, 0x1f, 0x5a, 0x1d, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x63, 0x2d, 0x67,
	0x65, 0x6e, 0x2d, 0x67, 0x6f, 0x2d, 0x77, 0x65, 0x62, 0x2f, 0x66, 0x69, 0x72, 0x73, 0x74, 0x3b,
	0x66, 0x69, 0x72, 0x73, 0x74, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_protoc_gen_go_web_first_first_proto_rawDescOnce sync.Once
	file_protoc_gen_go_web_first_first_proto_rawDescData = file_protoc_gen_go_web_first_first_proto_rawDesc
)

func file_protoc_gen_go_web_first_first_proto_rawDescGZIP() []byte {
	file_protoc_gen_go_web_first_first_proto_rawDescOnce.Do(func() {
		file_protoc_gen_go_web_first_first_proto_rawDescData = protoimpl.X.CompressGZIP(file_protoc_gen_go_web_first_first_proto_rawDescData)
	})
	return file_protoc_gen_go_web_first_first_proto_rawDescData
}

var file_protoc_gen_go_web_first_first_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_protoc_gen_go_web_first_first_proto_goTypes = []interface{}{
	(*HelloReq)(nil),        // 0: first.hello_req
	(*HelloResp)(nil),       // 1: first.hello_resp
	(*second.KissReq)(nil),  // 2: second.kiss_req
	(*second.ByeReq)(nil),   // 3: second.bye_req
	(*second.KissResp)(nil), // 4: second.kiss_resp
	(*second.ByeResp)(nil),  // 5: second.bye_resp
}
var file_protoc_gen_go_web_first_first_proto_depIdxs = []int32{
	0, // 0: first.test.hello:input_type -> first.hello_req
	2, // 1: first.test.kiss:input_type -> second.kiss_req
	3, // 2: first.test.bye:input_type -> second.bye_req
	1, // 3: first.test.hello:output_type -> first.hello_resp
	4, // 4: first.test.kiss:output_type -> second.kiss_resp
	5, // 5: first.test.bye:output_type -> second.bye_resp
	3, // [3:6] is the sub-list for method output_type
	0, // [0:3] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_protoc_gen_go_web_first_first_proto_init() }
func file_protoc_gen_go_web_first_first_proto_init() {
	if File_protoc_gen_go_web_first_first_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_protoc_gen_go_web_first_first_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*HelloReq); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_protoc_gen_go_web_first_first_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*HelloResp); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_protoc_gen_go_web_first_first_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_protoc_gen_go_web_first_first_proto_goTypes,
		DependencyIndexes: file_protoc_gen_go_web_first_first_proto_depIdxs,
		MessageInfos:      file_protoc_gen_go_web_first_first_proto_msgTypes,
	}.Build()
	File_protoc_gen_go_web_first_first_proto = out.File
	file_protoc_gen_go_web_first_first_proto_rawDesc = nil
	file_protoc_gen_go_web_first_first_proto_goTypes = nil
	file_protoc_gen_go_web_first_first_proto_depIdxs = nil
}
