//protoc -I ../../../pbex -I . --go-pbex_out=paths=source_relative:. *.proto
edition = "2024";
package test;
option go_package="github.com/chenjie199234/Corelib/pbex/test;test";
import option "pbex.proto";
service Test {
	rpc Hello(Helloreq)returns(Helloresp){
		option (pbex.method)="get";
		option (pbex.method)="crpc";
		option (pbex.method)="grpc";
		option (pbex.web_midwares)="user";
		option (pbex.web_midwares)="limit";
	}
	rpc World(Worldreq)returns(Worldresp){
		option (pbex.method)="post";
		option (pbex.method)="crpc";
		option (pbex.method)="grpc";
		option (pbex.web_midwares)="user";
		option (pbex.web_midwares)="limit";
	}
}
enum TestEnum {
	ENUMA=0;
	ENUMB=1;
    ENUMC=2;
}
message Helloreq{
	bool bl = 1[(pbex.bool_eq)=true];
	repeated bool bls = 2[(pbex.map_repeated_len_gt)=1,(pbex.map_repeated_len_lt)=4,(pbex.map_repeated_len_not_eq)=3];
	int32 i32=3[(pbex.int_gt)=0,(pbex.int_lt)=5,(pbex.int_not_in)=2,(pbex.int_not_in)=3];
	repeated int32 ri32=4[(pbex.int_lte)=-2147483648,(pbex.int_not_in)=1];
	uint32 ui32=5[(pbex.uint_gt)=1,(pbex.uint_lt)=4294967294,(pbex.uint_not_in)=10];
	repeated uint32 rui32=6[(pbex.map_repeated_len_gt)=2,(pbex.uint_lt)=1,(pbex.uint_not_in)=1];
	int64 i64=7[(pbex.int_gt)=-9223372036854775808,(pbex.int_lte)=9223372036854775806,(pbex.int_not_in)=1];;
	repeated int64 ri64=8;
	uint64 ui64=9;
	repeated uint64 rui64=10;
	bytes bs=11;
	repeated bytes rbs=12;
	string ss=13;
	repeated string rss=14[(pbex.string_bytes_reg_match)="^abc",(pbex.string_bytes_reg_not_match)="abc$"];
	float f=15[(pbex.float_gte)=1,(pbex.float_lte)=2,(pbex.float_not_in)=1.5,(pbex.float_not_in)=1];
	repeated float rf=16;
	double d=17;
	repeated double rd=18[(pbex.float_gte)=1,(pbex.float_lte)=2,(pbex.float_not_in)=2];
	TestEnum e=19;
	repeated TestEnum re=20;
	oneof o1{
		bool o1bl=21;
		int32 o1i32=22;
		uint32 o1ui32=23;
		int64 o1i64=24;
		uint64 o1ui64=25;
		bytes o1bs=26;
		string o1ss=27;
		float o1f=28;
		double o1d=29;
		TestEnum o1e=30;
		Helloresp o1m=31;
	}
	oneof o2{
		bool o2bl=41[(pbex.bool_eq)=true];
		int32 o2i32=42;
		uint32 o2ui32=43[(pbex.uint_gt)=10];
		int64 o2i64=44[(pbex.int_lt)=-1];
		uint64 o2ui64=45;
		bytes o2bs=46[(pbex.string_bytes_len_gt)=10,(pbex.string_bytes_len_lte)=100];
		string o2ss=47;
		float o2f=48[(pbex.float_gt)=1.1,(pbex.float_lte)=10.2];
		double o2d=49[(pbex.float_lt)=1];
		TestEnum o2e=50[(pbex.enum_in)=2,(pbex.enum_not_in)=0,(pbex.enum_gt)=1,(pbex.enum_lt)=3];
		Helloresp o2m=52[(pbex.message_not_nil)=true];
	}
}
message Helloresp{

}
message Worldreq{
	Helloreq m=1;
	repeated Helloreq rm=3;

	map<int32,int32> mi32_i32=4;
	map<int32,uint32> mi32_ui32=5;
	map<int32,int64> mi32_i64=6;
	map<int32,uint64> mi32_ui64=7;
	map<int32,bytes> mi32_bs=8;
	map<int32,string> mi32_ss=9;
	map<int32,float> mi32_f=10;
	map<int32,double> mi32_d=11;
	map<int32,TestEnum> mi32_e=12[(pbex.map_value_enum_gt)=0];
	map<int32,Helloreq> mi32_m=13;

	map<uint32,int32> mui32_i32=14;
	map<uint32,uint32> mui32_ui32=15;
	map<uint32,int64> mui32_i64=16;
	map<uint32,uint64> mui32_ui64=17;
	map<uint32,bytes> mui32_bs=18;
	map<uint32,string> mui32_ss=19[(pbex.map_value_string_bytes_reg_match)="^xyz"];
	map<uint32,float> mui32_f=20;
	map<uint32,double> mui32_d=21;
	map<uint32,TestEnum> mui32_e=22;
	map<uint32,Helloreq> mui32_m=23;

	map<int64,int32> mi64_i32=24;
	map<int64,uint32> mi64_ui32=25;
	map<int64,int64> mi64_i64=26;
	map<int64,uint64> mi64_ui64=27;
	map<int64,bytes> mi64_bs=28;
	map<int64,string> mi64_ss=29;
	map<int64,float> mi64_f=30;
	map<int64,double> mi64_d=31;
	map<int64,TestEnum> mi64_e=32;
	map<int64,Helloreq> mi64_m=33;

	map<uint64,int32> mui64_i32=34;
	map<uint64,uint32> mui64_ui32=35;
	map<uint64,int64> mui64_i64=36;
	map<uint64,uint64> mui64_ui64=37;
	map<uint64,bytes> mui64_bs=38;
	map<uint64,string> mui64_ss=39;
	map<uint64,float> mui64_f=40;
	map<uint64,double> mui64_d=41;
	map<uint64,TestEnum> mui64_e=42;
	map<uint64,Helloreq> mui64_m=43;

	map<string,int32> mss_i32=44;
	map<string,uint32> mss_ui32=45;
	map<string,int64> mss_i64=46;
	map<string,uint64> mss_ui64=47;
	map<string,bytes> mss_bs=48;
	map<string,string> mss_ss=49[
      (pbex.map_key_string_len_gt)=10,
      (pbex.map_key_string_reg_match)="^key",
      (pbex.map_key_string_reg_not_match)="xyz$",
      (pbex.map_value_string_bytes_len_lt)=50,
      (pbex.map_value_string_bytes_reg_match)="^value",
      (pbex.map_value_string_bytes_reg_not_match)="abc$"];
	map<string,float> mss_f=50;
	map<string,double> mss_d=51;
	map<string,TestEnum> mss_e=52;
	map<string,Helloreq> mss_m=53;

	oneof o{
		bool obl=54;
		int32 oi32=55;
		uint32 oui32=56;
		int64 oi64=57;
		uint64 oui64=58;
		bytes obs=59;
		string oss=60;
		float of=61;
		double od=62;
		TestEnum oe=63;
	}

	Selfnest s=64;
}
message Worldresp{
	Worldreq result1=1;
	Selfnest result2=2;
}
message Selfnest{
	Selfnest self=1;
	repeated Selfnest rself=3;
	map<int32,Selfnest> mi32_self=4;
	map<uint32,Selfnest> mui32_self=5;
	map<int64,Selfnest> mi64_self=6;
	map<uint64,Selfnest> mui64_self=7;
	map<string,Selfnest> mss_self=8;
}

